dependencies {
    implementation project(':conductor-common-persistence')
    implementation project(':conductor-common')
    implementation project(':conductor-core')

    compileOnly 'org.springframework.boot:spring-boot-starter'
    compileOnly "io.quarkus:quarkus-arc:${quarkusPlatformVersion}"

    implementation "com.google.guava:guava:${revGuava}"
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "com.fasterxml.jackson.core:jackson-core"
    implementation "org.apache.commons:commons-lang3"

    implementation "com.clickhouse:clickhouse-jdbc:${revClickHouse}"

    testImplementation 'org.springframework.retry:spring-retry'
    testImplementation "org.apache.groovy:groovy-all:${revGroovy}"
    testImplementation project(':conductor-server')
    testImplementation project(':conductor-test-util').sourceSets.test.output
    testImplementation project(':conductor-common-persistence').sourceSets.test.output
    testImplementation "org.testcontainers:clickhouse:${revTestContainer}"
    testImplementation "org.awaitility:awaitility:${revAwaitility}"
}

test {
    maxParallelForks = 1
}
