plugins {
    id 'io.quarkus'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-rest'
    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-spring-di'
    implementation 'io.quarkus:quarkus-spring-web'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-agroal'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation "org.xerial:sqlite-jdbc:${sqliteJdbc}"
    implementation 'io.quarkus:quarkus-jdbc-postgresql'

    implementation project(':conductor-common')
    implementation project(':conductor-core')
    implementation project(':conductor-rest')
    implementation project(':conductor-sqlite-persistence')

    implementation "org.flywaydb:flyway-core:${revFlyway}"
    implementation 'org.springframework.retry:spring-retry'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation "com.google.protobuf:protobuf-java:${revProtoBuf}"
    testImplementation 'junit:junit:4.13.2'
}
