# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=${CONDUCTOR_QUEUE_TYPE:redis_standalone}
#Kalau pakai sentinel diganti dengan 
# conductor.queue.type=redis_sentinel
conductor.external-payload-storage.type=postgres
conductor.app.taskExecutionPostponeDuration=10s

# Database connectivity
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://postgresdb:5432/postgres}
quarkus.datasource.url=${DB_URL:jdbc:postgresql://postgresdb:5432/postgres}
quarkus.datasource.username=${DB_USER:conductor}
quarkus.datasource.password=${DB_PASS:conductor}
conductor.postgres.deadlockRetryMax=3
conductor.postgres.taskDefCacheRefreshInterval=60s
conductor.postgres.asyncMaxPoolSize=12
conductor.postgres.asyncWorkerQueueSize=100
#Setingan redis standalone
conductor.redis.hosts=${REDIS_HOSTS:host.docker.internal:6379:us-east-1c}
#kalau pakai redis sentinel
# conductor.redis.hosts=redis-sentinel-1:26379:us-east-1c;redis-sentinel-2:26379:us-east-1c;redis-sentinel-3:26379:us-east-1c
#conductor.redis.sentinelMasterName=mymaster
#conductor.redis.availabilityZone=us-east-1c
#--- sampai disini kalau pakai redis sentinel

conductor.redis-lock.serverAddress=${REDIS_LOCK_SERVER:redis://host.docker.internal:6379}
conductor.redis.taskDefCacheRefreshInterval=2
conductor.redis.workflowNamespacePrefix=conductor
conductor.redis.queueNamespacePrefix=conductor_queues
conductor.redis.ssl=false
management.health.redis.enabled=true

conductor.workflow-execution-lock.type=redis 
conductor.app.workflowExecutionLockEnabled=true
conductor.app.lockTimeToTry=500

# Indexing Properties
conductor.indexing.enabled=true
conductor.indexing.type=postgres
# Required to disable connecting to elasticsearch.
conductor.elasticsearch.version=0

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=false

# Shorten postpone duration to speed up concurrent execution limit tests (default is 60s)
conductor.app.taskExecutionPostponeDuration=10s

# File storage
conductor.file-storage.enabled=true
conductor.file-storage.type=conductor
