# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=redis_standalone
conductor.external-payload-storage.type=postgres
conductor.app.taskExecutionPostponeDuration=10s

# Database connectivity
quarkus.datasource.url=${DB_URL:-jdbc:postgresql://postgresdb:5432/postgres}
quarkus.datasource.username=conductor
quarkus.datasource.password=conductor


# Indexing Properties
conductor.indexing.enabled=true
conductor.indexing.type=postgres
# Required to disable connecting to elasticsearch.
conductor.elasticsearch.version=0

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=false

# Shorten postpone duration to speed up concurrent execution limit tests (default is 60s)
conductor.app.taskExecutionPostponeDuration=10s

# File storage
conductor.file-storage.enabled=true
conductor.file-storage.type=conductor
